apiVersion: v1
kind: Secret
metadata:
  name: {{ include "barrelman.fullname" . }}
  namespace: kube-system
  labels:
{{ include "barrelman.labels" . | indent 4 }}
type: Opaque
data:
  credentials.json: |-
   {{ .Values.barrelman.gce_service_account | nindent 4 }}