apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "barrelman.fullname" . }}
  namespace: kube-system
  labels:
{{ include "barrelman.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "barrelman.fullname" . }}
  labels:
{{ include "barrelman.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "watch", "get", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "barrelman.fullname" . }}
  labels:
{{ include "barrelman.labels" . | indent 4 }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "barrelman.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "barrelman.fullname" . }}
    namespace: kube-system
