# Default values for barrelman.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "traumfewo/barrelman"
  tag: "v0.2.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# Barrelman configuration
barrelman:
  gce_service_account: "undefined"
  resync_period: "2h"
  verbosity: "2"
  necWorkers: "4"
  scWorkers: "2"
  nodePortSvc: false
  remote:
    project: "undefined"
    zone: "undefined"
    cluster_name: "undefined"

resources:
  limits:
    cpu: 50m
    memory: 25Mi
  requests:
    cpu: 50m
    memory: 25Mi

nodeSelector: {}

tolerations: []

affinity: {}
